package com.VetSystem.RestAPI.entity;
// Generated 17-sep-2019 16:08:27 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * Checkup generated by hbm2java
 */
@Entity
@Table
public class Checkup  implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "checkupid", updatable = false) 
    private int checkupid;
    
    @JsonIgnore
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "vetid")
    private Vet vet;
    
    @Column(insertable = false, updatable = false)
    private int vetid;
    
    @DateTimeFormat(pattern = "dd/MM/yyyy")
    @Column
    private Date checkupdate;
    
    @Column
    private String isactive;
    
    @Column(name = "creationdate", insertable = false, updatable = false)
    private Date creationdate;
    
    @Column(name = "createdby", insertable = false, updatable = false)
    private String createdby;
    
    @Column(name = "lastupdate", insertable = false)
    private Date lastupdate;
    
    @Column(name = "updateby", insertable = false)
    private String updateby;
    
    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "checkup")//, cascade = CascadeType.ALL)
    private Set<Checkupreport> checkupreports = new HashSet<>();

    public Checkup() {
    }

	
    public Checkup(int checkupid, int vetid, String isactive, Date creationdate, String createdby) {
        this.checkupid = checkupid;
        this.vetid = vetid;
        this.isactive = isactive;
        this.creationdate = creationdate;
        this.createdby = createdby;
    }
    public Checkup(int checkupid, int vetid, Vet vet, Date checkupdate, String isactive, Date creationdate, String createdby, Date lastupdate, String updateby, Set checkupreports) {
       this.checkupid = checkupid;
       this.vetid = vetid;
       this.vet = vet;
       this.checkupdate = checkupdate;
       this.isactive = isactive;
       this.creationdate = creationdate;
       this.createdby = createdby;
       this.lastupdate = lastupdate;
       this.updateby = updateby;
       this.checkupreports = checkupreports;
    }
   
    public int getCheckupid() {
        return this.checkupid;
    }
    
    public void setCheckupid(int checkupid) {
        this.checkupid = checkupid;
    }

    public int getVetid() {
        return vetid;
    }

    public void setVetid(int vetid) {
        this.vetid = vetid;
    }
    
    public Vet getVet() {
        return this.vet;
    }
    
    public void setVet(Vet vet) {
        this.vet = vet;
    }
    public Date getCheckupdate() {
        return this.checkupdate;
    }
    
    public void setCheckupdate(Date checkupdate) {
        this.checkupdate = checkupdate;
    }
    public String getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(String isactive) {
        this.isactive = isactive;
    }
    public Date getCreationdate() {
        return this.creationdate;
    }
    
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }
    public Date getLastupdate() {
        return this.lastupdate;
    }
    
    public void setLastupdate(Date lastupdate) {
        this.lastupdate = lastupdate;
    }
    public String getUpdateby() {
        return this.updateby;
    }
    
    public void setUpdateby(String updateby) {
        this.updateby = updateby;
    }
    public Set getCheckupreports() {
        return this.checkupreports;
    }
    
    public void setCheckupreports(Set checkupreports) {
        this.checkupreports = checkupreports;
    }

    @PreUpdate
    public void preUpdate(){
        this.lastupdate = new Date();
        this.updateby = "postgres";
    }

}


