package com.VetSystem.RestAPI.entity;
// Generated 17-sep-2019 16:08:27 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import org.hibernate.annotations.Type;

/**
 * Checkupreport generated by hbm2java
 */
@Entity
@Table
public class Checkupreport  implements java.io.Serializable {


    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "checkupreportid", updatable = false) 
    private int checkupreportid;
    
    //@JsonIgnore
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "checkupid")
    private Checkup checkup;
    
    @Column(insertable = false, updatable = false)
    private int checkupid;
    
    
    //@JsonIgnore
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "petid")
    private Pet pet;
    
    @Column(insertable = false, updatable = false)
    private int petid;
    
    @Lob
    @Type(type="org.hibernate.type.BinaryType") 
    @Column
    private byte[] reportnotes;
    
    @Lob
    @Type(type="org.hibernate.type.BinaryType") 
    @Column
    private byte[] reportattachment;
    @Column
    private String isactive;
    
    @Column(name = "creationdate", insertable = false, updatable = false)
    private Date creationdate;
    
    @Column(name = "createdby", insertable = false, updatable = false)
    private String createdby;
    
    @Column(name = "lastupdate", insertable = false)
    private Date lastupdate;
    
    @Column(name = "updateby", insertable = false)
    private String updateby;

    public Checkupreport() {
    }

	
    public Checkupreport(int checkupreportid, int petid, int checkupid, String isactive, Date creationdate, String createdby) {
        this.checkupreportid = checkupreportid;
        this.petid = petid;
        this.checkupid = checkupid;
        this.isactive = isactive;
        this.creationdate = creationdate;
        this.createdby = createdby;
    }
    public Checkupreport(int checkupreportid, int petid, int checkupid, Checkup checkup, Pet pet, byte[] reportnotes, byte[] reportattachment, String isactive, Date creationdate, String createdby, Date lastupdate, String updateby) {
       this.checkupreportid = checkupreportid;
       this.petid = petid;
       this.checkupid = checkupid;
       this.checkup = checkup;
       this.pet = pet;
       this.reportnotes = reportnotes;
       this.reportattachment = reportattachment;
       this.isactive = isactive;
       this.creationdate = creationdate;
       this.createdby = createdby;
       this.lastupdate = lastupdate;
       this.updateby = updateby;
    }
   
    public int getCheckupreportid() {
        return this.checkupreportid;
    }
    
    public void setCheckupreportid(int checkupreportid) {
        this.checkupreportid = checkupreportid;
    }

    public int getCheckupid() {
        return checkupid;
    }

    public void setCheckupid(int checkupid) {
        this.checkupid = checkupid;
    }

    public int getPetid() {
        return petid;
    }

    public void setPetid(int petid) {
        this.petid = petid;
    }
    
    public Checkup getCheckup() {
        return this.checkup;
    }
    
    public void setCheckup(Checkup checkup) {
        this.checkup = checkup;
    }
    public Pet getPet() {
        return this.pet;
    }
    
    public void setPet(Pet pet) {
        this.pet = pet;
    }
    public byte[] getReportnotes() {
        return this.reportnotes;
    }
    
    public void setReportnotes(byte[] reportnotes) {
        this.reportnotes = reportnotes;
    }
    public byte[] getReportattachment() {
        return this.reportattachment;
    }
    
    public void setReportattachment(byte[] reportattachment) {
        this.reportattachment = reportattachment;
    }
    public String getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(String isactive) {
        this.isactive = isactive;
    }
    public Date getCreationdate() {
        return this.creationdate;
    }
    
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }
    public Date getLastupdate() {
        return this.lastupdate;
    }
    
    public void setLastupdate(Date lastupdate) {
        this.lastupdate = lastupdate;
    }
    public String getUpdateby() {
        return this.updateby;
    }
    
    public void setUpdateby(String updateby) {
        this.updateby = updateby;
    }

    @PreUpdate
    public void preUpdate(){
        this.lastupdate = new Date();
        this.updateby = "postgres";
    }

}


