package com.VetSystem.RestAPI.entity;
// Generated 17-sep-2019 16:08:27 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import org.hibernate.annotations.Type;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * Pet generated by hbm2java
 */
@Entity
@Table
public class Pet  implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "petid", updatable = false)
    private int petid;
    
    @JsonIgnore
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ownerid")
    private Owner owner;
    
    @Column(insertable = false, updatable = false)
    private int ownerid;
    
    @Column
    private String name;
    
    @Column
    private String animaltype;
    
    @Column
    private String breedname;
    
    @Column
    private String birthplace;
    
    @DateTimeFormat(pattern = "dd/MM/yyyy")
    @Column
    private Date birthdate;
    
    @Lob
    @Type(type="org.hibernate.type.BinaryType") 
    @Column
    private byte[] photo;
    
    @Column
    private String isactive;
    
    @Column(name = "creationdate", insertable = false, updatable = false)
    private Date creationdate;
    
    @Column(name = "createdby", insertable = false, updatable = false)
    private String createdby;
    
    @Column(name = "lastupdate", insertable = false)
    private Date lastupdate;
    
    @Column(name = "updateby", insertable = false)
    private String updateby;
    
    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pet")//, cascade = CascadeType.ALL)
    private Set<Checkupreport> checkupreports = new HashSet<>();

    public Pet() {
    }

	
    public Pet(int petid, int ownerid, String name, String animaltype, String breedname, String birthplace, Date birthdate, String isactive, Date creationdate, String createdby) {
        this.petid = petid;
        this.ownerid = ownerid;
        this.name = name;
        this.animaltype = animaltype;
        this.breedname = breedname;
        this.birthplace = birthplace;
        this.birthdate = birthdate;
        this.isactive = isactive;
        this.creationdate = creationdate;
        this.createdby = createdby;
    }
    public Pet(int petid, int ownerid, Owner owner, String name, String animaltype, String breedname, String birthplace, Date birthdate, byte[] photo, String isactive, Date creationdate, String createdby, Date lastupdate, String updateby, Set checkupreports) {
       this.petid = petid;
       this.ownerid = ownerid;
       this.owner = owner;
       this.name = name;
       this.animaltype = animaltype;
       this.breedname = breedname;
       this.birthplace = birthplace;
       this.birthdate = birthdate;
       this.photo = photo;
       this.isactive = isactive;
       this.creationdate = creationdate;
       this.createdby = createdby;
       this.lastupdate = lastupdate;
       this.updateby = updateby;
       this.checkupreports = checkupreports;
    }
   
    public int getPetid() {
        return this.petid;
    }
    
    public void setPetid(int petid) {
        this.petid = petid;
    }

    public int getOwnerid() {
        return ownerid;
    }

    public void setOwnerid(int ownerid) {
        this.ownerid = ownerid;
    }
    
    public Owner getOwner() {
        return this.owner;
    }
    
    public void setOwner(Owner owner) {
        this.owner = owner;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAnimaltype() {
        return this.animaltype;
    }
    
    public void setAnimaltype(String animaltype) {
        this.animaltype = animaltype;
    }
    public String getBreedname() {
        return this.breedname;
    }
    
    public void setBreedname(String breedname) {
        this.breedname = breedname;
    }
    public String getBirthplace() {
        return this.birthplace;
    }
    
    public void setBirthplace(String birthplace) {
        this.birthplace = birthplace;
    }
    public Date getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }
    public byte[] getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }
    public String getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(String isactive) {
        this.isactive = isactive;
    }
    public Date getCreationdate() {
        return this.creationdate;
    }
    
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }
    public Date getLastupdate() {
        return this.lastupdate;
    }
    
    public void setLastupdate(Date lastupdate) {
        this.lastupdate = lastupdate;
    }
    public String getUpdateby() {
        return this.updateby;
    }
    
    public void setUpdateby(String updateby) {
        this.updateby = updateby;
    }
    public Set getCheckupreports() {
        return this.checkupreports;
    }
    
    public void setCheckupreports(Set checkupreports) {
        this.checkupreports = checkupreports;
    }

    @PreUpdate
    public void preUpdate(){
        this.lastupdate = new Date();
        this.updateby = "postgres";
    }

}


